---

system_packages:
  - varnish
  - nginx
  - openssl

# recommended to be same (or double) the number of processors
nginx_worker_processes: 16

# default is 1024
nginx_worker_connections: 4096

# default is 65
nginx_keepalive_timeout: 65

# this is the certificate name to be used in the Nginx config
nginx_ssl_certificate_name_to_use: multi_domain_feb_2014

# this is the certificate to generate a key and csr for
nginx_ssl_certificate_name_to_install: multi_domain_feb_2014

ssl_certificate_domains:
  - learningequality.org
  - kalite.learningequality.org
  - kalite.adhocsync.com
  - forums.learningequality.org

primary_ssl_certificate_domain: learningequality.org


allowed_ports:
  - 80
  - 443
  - 7007
  - 8008


proxy_backends:

  - name: citadel_fle_site
    host: citadel
    port: "{{ citadel_flesite_port }}"

  - name: keep_ka_lite
    host: keep
    port: "{{ keep_kalite_port }}"

  - name: scriptorium_forums
    host: scriptorium
    port: 80

  - name: old_adhocsync_dev_server
    host: 174.129.228.112
    port: 7007


virtual_hosts:

  - hosts:
      - learningequality.org
    locations:
      - path: /
        backend: citadel_fle_site
        varnish: yes
    force_https: yes

  # this one is only necessary because of the gatehouse link Dylan sent out for the internships page; can be deleted later
  - hosts:
      - gatehouse.learningequality.org
    locations:
      - path: /
        redirect: https://learningequality.org$request_uri

  - hosts:
      - kalite.learningequality.org
    locations:
      - path: /
        backend: keep_ka_lite
      - path: = /
        backend: keep_ka_lite
        varnish: yes
      - path: /faq
        backend: keep_ka_lite
        varnish: yes
      - path: /content
        backend: keep_ka_lite
        varnish: yes
    force_https: yes

  - hosts:
      - kalite.adhocsync.com
      - adhocsync.com
    locations:
      - path: = /
        redirect: https://kalite.learningequality.org
      - path: /
        backend: keep_ka_lite
    allow_https: yes

  - hosts:
      - forums.learningequality.org
    locations:
      - path: /
        backend: scriptorium_forums
    force_https: yes

  - hosts:
      - kalite.learningequality.org
    ports: ["7007", "8008 ssl"]
    locations:
      - path: /
        backend: old_adhocsync_dev_server
    allow_https: yes

  - ports:
      - "80 default"
    locations:
      - path: /
        redirect: https://learningequality.org/