# benchmarking.yml
---
- hosts: benchmarking
  vars: 
      githubId: 'fle-internal'
      targetSite: 'http://demo.learningequality.org/'
      logUrl: 'locust-master.log'
      masterHost: '192.237.171.38'
  roles:
    - locust-deploy
    - locust-master
    - locust-slave
