---
# Create a new user on a server, and add them to the sudoers group
# ('host' and 'user' must be specified)

# To create as a root user, do something like:
# ansible-playbook -i hosts create_authorized_user.yml -e "host=blah user=_new_user_name_ ansible_ssh_user=root" --ask-pass

- hosts: '{{ host }}'
  sudo: yes

  vars_prompt:
    - name: password
      prompt: "Enter password for new user"
      private: yes
      encrypt: "md5_crypt"
      confirm: yes
      salt_size: 7

  tasks:
  - name: Create the user and add them to the sudoers group
    user: "name='{{ user }}' password='{{ password }}' groups='sudo' shell='/bin/bash'"
  - name: Ensure sudoers don't need to enter password
    lineinfile: "dest=/etc/sudoers state=present regexp='^%sudo[\t ]+ALL' line='%sudo ALL=(ALL:ALL) NOPASSWD: ALL' validate='visudo -cf %s'"
