---

- hosts: localhost
  vars:
    - ka_lite_distributed_git_branch: 0.13.x
    - kalite_source_dest: /vagrant/source
    - docs_output_dir: /vagrant/output
    - docs_html_host_dir: /vagrant/www/html
    - docs_pdf_host_dir: /vagrant/www/pdfs
  roles:
    - common
    - server
    - docsbuilder