---

- hosts: field
  vars:
    - ka_lite_distributed_git_branch: 0.13.x
    - kalite_source_dest: ~/docs/ka-lite-source
    - docs_output_dir: ~/docs/output
    - docs_html_host_dir: /usr/share/nginx/html/docs
    - docs_pdf_host_dir: /usr/share/nginx/html/docspdf
  roles:
    - common
    - server
    - docsbuilder
    - { role: docsbuilder, ka_lite_distributed_git_branch: develop, docs_html_host_dir: /usr/share/nginx/html/develop/docs, docs_pdf_host_dir: /usr/share/nginx/html/develop/docspdf }