---
- hosts: globe
  vars_files:
    - [roles/keep/vars/secrets.yml, roles/keep/vars/main.yml]
  vars:
    ka_lite_central_db_name: "ka_lite_staging"  # TODO(bcipolli): change to ka_lite_central_staging later.
  roles:
    - common
    - server
    - keep
