---
- hosts: localhost
  roles:
    - common
    - test
  # tasks:
  #   - name: print something
  #     command: 'echo "{{ system_packages }}"'

  #   - name: do some randomness
  #     command: 'echo "qqq"'
  #     register: randomness
  #     retries: 5
  #     delay: 0.1

  # handlers:
  #   - name: randomness
  #     shell: "echo {{ item }}"

  #     with_random_choice:
  #     - "go through the door"
  #     - "drink from the goblet"
  #     - "press the red button"
  #     - "do nothing"

