---

- name: Clone the ka-lite git repository and checkout the desired branch.
  git: repo=https://github.com/learningequality/ka-lite.git version={{ ka_lite_distributed_git_branch }} dest={{ kalite_source_dest }}
  sudo: yes

- name: Grab translatable messages from the docs
  command: make -C {{ kalite_source_dest }}/sphinx-docs gettext

- name: Set up po file structure for each supported language
  command: sphinx-intl update -p {{ kalite_source_dest }}/sphinx-docs/_build/locale -c {{ kalite_source_dest}}/sphinx-docs/conf.py -l {{ item }}
  with_items: available_languages

- name: Grab translated pofiles for the docs and put them in the proper directory
  command: echo "Please implement me :( :( :("

- name: Build the html docs in each available language
  command: env SPHINX_SS_USE_PVD=true sphinx-build -b html -Dlanguage={{ item }} {{ kalite_source_dest }}/sphinx-docs {{ docs_output_dir}}/html/{{ item }}
  sudo: yes
  with_items: available_languages

- name: Build the latex docs in each available language (so we can make pdfs)
  command: env SPHINX_SS_USE_PVD=true sphinx-build -b latex -Dlanguage={{ item }} {{ kalite_source_dest }}/sphinx-docs {{ docs_output_dir}}/latex/{{ item }}
  sudo: yes
  with_items: available_languages

- name: Build the pdfs from the latex
  command: make -C {{ docs_output_dir }}/latex/en all-pdf
  sudo: yes
  with_items: available_languages

- name: Push the built docs to the server (a no-op right now)
  shell: echo "Make me :( :( :("