- name: Add the docker repository key.
  shell: apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 36A1D7869245C8950F966E92D8576A8BA88D21E9
  sudo: yes

- name: Add the docker PPA.
  shell: sh -c "echo deb https://get.docker.io/ubuntu docker main\ > /etc/apt/sources.list.d/docker.list"
  sudo: yes

- name: Install docker.
  apt: pkg=lxc-docker state=installed update-cache=yes
  sudo: yes