---

- name: Ensure the downloads directory exists and set it as belonging to the www-data user.
  file: dest={{ download_folder_location }} owner=www-data state=directory mode=777
  sudo: yes

- name: Setup general Nginx config file.
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  sudo: yes
  notify: restart nginx
  tags:
    - nginx

- name: Setup Nginx site config file.
  template: src=001-staticfiles.j2 dest=/etc/nginx/sites-available/001-staticfiles
  sudo: yes
  notify: restart nginx
  tags:
    - nginx

- name: Enable the KA Lite Nginx site.
  file: dest=/etc/nginx/sites-enabled/001-staticfiles src=/etc/nginx/sites-available/001-staticfiles state=link
  sudo: yes
  notify: restart nginx
  tags:
    - nginx

- name: Remove default dummy Nginx conf file.
  file: dest=/etc/nginx/sites-enabled/default state=absent
  sudo: yes
  notify: restart nginx
  tags:
    - nginx

