---
- name: restart apache2
  service: name=apache2 state=restarted
  sudo: yes
- name: restart nginx
  service: name=nginx state=restarted
  sudo: yes
- name: restart varnish
  service: name=varnish state=restarted
  sudo: yes
- name: restart sshd
  service: name=sshd state=restarted
  sudo: yes
