---

- name: Set hostname to inventory name.
  hostname: name={{ inventory_hostname }}
  sudo: yes

- name: Set the remote /etc/hosts to point to each of the servers in the Ansible hosts file
  template: src=hosts.j2 dest=/etc/hosts
  sudo: yes
  when: set_hosts_file is defined and set_hosts_file

- name: Install common required system packages.
  apt: pkg={{ item }} state=installed update-cache=yes
  with_items: common_system_packages
  sudo: yes

- name: Install role-specific required system packages.
  apt: pkg={{ item }} state=installed update-cache=yes
  with_items: system_packages
  when: system_packages is defined
  sudo: yes

- name: Install role-specific required Python packages.
  pip: name={{ item }}
  with_items: python_packages
  when: python_packages is defined
  sudo: yes

- name: Set timezone to America/Los_Angeles.
  copy: src=timezone dest=/etc/timezone
  notify: update tzdata
  sudo: yes

- name: Add SSH ports to ufw rules.
  ufw: policy=allow to_port={{ item }}
  with_items:
    - "{{ alternate_sshd_port }}"
    - 22
  sudo: yes

- name: Limit SSH login attempts.
  ufw: policy=limit to_port={{ alternate_sshd_port }}
  sudo: yes

- name: Add role-specific ports to ufw rules.
  ufw: policy=allow to_port={{ item }}
  with_items: allowed_ports
  when: allowed_ports is defined
  sudo: yes
  tags:
    - proxy

- name: Check UFW status.
  command: ufw status
  sudo: yes
  register: ufw_status
  changed_when: False

- name: Enable UFW.
  command: ufw --force enable
  sudo: yes
  when: "ufw_status.stdout is defined and 'Status: inactive' in ufw_status.stdout"

