---

- name: Load the list of authorized users for the current host.
  set_fact: 'authorized_users="{{ permissions[inventory_hostname] }}"'

- name: Set hostname to inventory name.
  hostname: name={{ inventory_hostname }}
  sudo: yes

- name: Set the remote /etc/hosts to point to each of the servers in the Ansible hosts file
  template: src=hosts.j2 dest=/etc/hosts
  sudo: yes
  when: set_hosts_file is defined and set_hosts_file

- name: Install common required system packages.
  apt: pkg={{ item }} state=installed update-cache=yes
  with_items: common_system_packages
  sudo: yes

- name: Install role-specific required system packages.
  apt: pkg={{ item }} state=installed update-cache=yes
  with_items: system_packages
  when: system_packages is defined
  sudo: yes

- name: Install role-specific required Python packages.
  pip: name={{ item }}
  with_items: python_packages
  when: python_packages is defined
  sudo: yes

- name: Set timezone to America/Los_Angeles.
  copy: src=timezone dest=/etc/timezone
  notify: update tzdata
  sudo: yes

- name: Add SSH ports to ufw rules.
  ufw: policy=allow to_port={{ item }}
  with_items:
    - "{{ alternate_sshd_port }}"
    - 22
  sudo: yes

- name: Limit SSH login attempts.
  ufw: policy=limit to_port={{ alternate_sshd_port }}
  sudo: yes

- name: Add role-specific ports to ufw rules.
  ufw: policy=allow to_port={{ item }}
  with_items: allowed_ports
  when: allowed_ports is defined
  sudo: yes
  tags:
    - proxy

- name: Check UFW status.
  command: ufw status
  sudo: yes
  register: ufw_status
  changed_when: False

- name: Enable UFW.
  command: ufw --force enable
  sudo: yes
  when: "ufw_status.stdout is defined and 'Status: inactive' in ufw_status.stdout"

- name: Generate random password (won't actually get used).
  local_action: shell openssl passwd -in /dev/urandom | head -1
  changed_when: no
  register: password

- name: Add accounts for admins and add them to the sudoers group.
  user: "name='{{ item }}' password='{{ password.stdout }}' groups='sudo' shell='/bin/bash' update_password='on_create'"
  with_items: admins.keys()
  sudo: yes

- name: Create the users' .ssh directories.
  file: "dest=/home/{{ item }}/.ssh owner={{ item }} state=directory"
  with_items: admins.keys()
  sudo: yes

- name: Add authorized_keys for admin SSH logins.
  template: "src=authorized_keys.j2 dest=/home/{{ item }}/.ssh/authorized_keys"
  when: item in authorized_users
  with_items: admins.keys()
  sudo: yes
  sudo_user: "{{ item }}"
  notify:
    - restart ssh

- name: Remove authorized_keys for unauthorized admin SSH logins.
  copy: "content='' dest=/home/{{ item }}/.ssh/authorized_keys"
  when: item not in authorized_users
  with_items: admins.keys()
  sudo: yes
  sudo_user: "{{ item }}"
  notify:
    - restart ssh

- name: Ensure sudoers don't need to enter password
  lineinfile: "dest=/etc/sudoers state=present regexp='^%sudo[\t ]+ALL' line='%sudo ALL=(ALL:ALL) NOPASSWD: ALL' validate='visudo -cf %s'"
  sudo: yes
