---

system_packages:
  - openssl
  - python-m2crypto
  - python-mysqldb
  - apache2
  - libapache2-mod-wsgi
  - mysql-client

python_packages:
  - MySQL-python

apache_request_timeout: 300

apache_StartServers: 40
apache_MinSpareThreads: 50
apache_MaxSpareThreads: 100
apache_ThreadLimit: 128
apache_ThreadsPerChild: 100
apache_MaxClients: 500
apache_MaxRequestsPerChild: 2000

ka_lite_central_git_branch: develop
ka_lite_central_path: /var/www/ka-lite-central

postmark_sender: "kalite@learningequality.org"

ka_lite_central_db_name: "ka_lite_central"
ka_lite_central_db_user: "ka_lite_central"

ufw_enabled: yes

ufw_allowed_ports:
  - "{{ keep_ka_lite_central_port }}"

ka_crowdin_project_id: "khanacademy"

crowdin_project_id: "ka-lite"

lang_pack_versions:
  - 0.10.3
  - 0.11.1
