---

system_packages:
  - xvfb
  - texlive-latex-recommended
  - texlive-latex-extra
  - texlive-fonts-recommended
  - python

python_packages:
  - sphinx
  - sphinx-intl
  - pyvirtualdisplay

available_languages:
  - en
  - eo