---

common_system_packages:
  - git
  - python-pip
  - htop
  - iotop
  - unzip

db_server_host: 48e2bc57fa7b4d9d864b165c70369c434cd8c457.rackspaceclouddb.com

citadel_flesite_port: 8000

keep_kalite_port: 8008