---

common_system_packages:
  - git
  - python-pip
  - htop
  - iotop
  - unzip

common_python_packages:
  - ipython==0.11

db_server_host: 48e2bc57fa7b4d9d864b165c70369c434cd8c457.rackspaceclouddb.com

citadel_flehome_port: 8000

keep_ka_lite_central_port: 8008

admins:
  aron:
    keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDSuLeJW1/vejKZ3MJIdNpEJey04CdoT8Edii8pL8JHKlQysLxmNzUq698iCeNJ2TWB69AZYR3QLTiwfAPJ1KXN2nw5KycAkOajST92QsYFcK0bDBIjXc71aZ+H/9Z8ICZtqyPGO4h6KmjKXXjYci9IEacTHP7l2LeoVVfwFTDXNxxmiMCTiC8cWRjquu1TQy2j/AC7tsA8zmzmmdfUS5flNda42nYDCnRLkS74DPCEhLvutaNdQP2/FuNeA+p4X28PDN5AwUi28UlOagMbSD8uJcmdrTrlvukdbtwA1M/iJAroCQOCVMzz/XPVvvWp0y530hQXzNzLNkXIuTo3D4Ut aron@kaligayahan
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDTJd5zZbDiCVEUxz+fbH8bBDPbO5D8wcuV5Q6s8MHw8mrRtC7Tm48Wv7ICBvsGrGbasfmL0tCpxCNBGVFror49js5uNxvpn6A3oH4VtW/f71J4CMu76zUWO1gbtgtCysv4qr+z2h3Jg0Wr5eRF8M7+kQaFIVEUO5fF0L/+SI/DQP7mvCqP5jZaKDg5UbZ5a++aVi85ZLzL3J+QX5TJinZ7bGbXMG+GMgw3vGb1VH87HQB+nycu8PypamYcmNONGeSqji6GrUB1u0MzBFo/jTEHUtjUSBTyJ7bHeKYXV7RYxY1NAp93tFvaDVc3NmzGeP3RDGZRI1htckpFCR2/+pFP aron@felicidad
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDXwikEo63L4EJiUE4k7EInZMjaRSyBf5eIah/RrIBVXpmDh+H4C3xnvFLSdq0AV7rFWr6lsX1SHbnJOKjutqBx8h22f5KW/fCmGNB4S71yuAs38t9G2Lt3AqOYf8yyo3Hu0C1TWpIeGwK/GGpq1+cgq7W3FDK8QaBj3TapOJUThAN+MbKL9yaaCCAq8c/MojMH8/qL8BE8TAH5b1/k/nk963CXPsD66mkOWAHCsBmzLNtmspUL563/HyPLaRMxaglciTIyTQOvdXR695vlm3P4HvptA20nplSuBN4SO+/P8JET0u0d+3SGZy9rJd0I162p+9BR4NokqVIZ8oc/ySHN aron@kagalakan
  jamalex:
    keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDvZbFyn5l3+JbD21ooVJ6pOoo7HaazEWiK3VAANgk0VaHz4K2PqPBOtFp5Geg4EixqHFF11Wa7jMTFw4svi6wAm3hLJeLi6Ghja//APRIHsKnVSR/2RPxoTlwrgmtZuZOr1xKdpALn7YulcItpCKvcFQWRg+J3ove1IJCxlFr/k7dDo2P8Ny18ULtLlaugyHQ3TE0kUP9W5hYkYFwMAr8Vvuuca7oXJXqXoISwkgRElGXPorMtWOmfyLWOV413kQvX21hz7sU6kyxStLxP9gZwwdZ9IjQ3tCucnAo5NLMYiOD99L3aevs59+3gihdIa9QDPp9b5lPICEC0tNruYX51 jamalex@ace
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDgcmGfhjcENw4gUUD4Dhwyl0NmoQodtWSz1NB04P9ktXgXMljr8Hn8VQtZrG2Eu8HOdQI3p5Fd9cgRuD7W+07p/9sF1HnmAf+OJ5luCzmEzZpakXqOBULzyNuR4aPgX1z7HskDCETi3X9nY88R0PWP440MCfiffkM66tqV70PEOWw+87mR10SnsUdXYzitZ0pAt1JOTsZE+tgygV1yK4CTUf7r8HT/y+GNte0ixJ5MLvh8bXyBU2j9i6AAyNqG9IZOj5lCM0NbuTdjJz6rzGOIysvPqeoiTb8NbGi4PwcnPMznVhs7zOI+B8MGP1oMQPd5YLBDSbs2wyImuQ4D5WyD jamalex@fett
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC9MX6JL2X9ZI0jsIS9NfGt688Q/v1ZrDg7nQ43tAjfOL1VZ7z1njc/01p/ymKP6P3dueBrbPUkyOWpaTu8BmPFz11TLcUCUkJ4OhoGlOQ+KpWgU+cATz5386WIAdmu903p3DaeNkte7QT71nJAVfLolYTCL21hRjAjBhFsSbCeVJ5Y8ppT2LiE94waPBAIQF/crQdoVGLgnU4uP0YgtvpMWUIQWfpmUB+ck/b9vMJVE4Wtd8s0XL0z5VvLnzfwCPCJK03AZXqVpo65OIBLt3DvHqM50fPCQc7Qq5q6cFU4IZF+xgBbPf6aZr6MJZiWHskDtFazWOUS2vSgVX4YdjUb jamalex@keep
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0pX4n0PkEzySjH2FR4gQ9TJIN54JQ2Mm+zpHKatqOSl9sUXrPZKO+dCfwNVfa/jJwg0YELEs7fsq1CCoVYzZ0AbH/OC0U/iHJKumjB9d7T/zKL4FJ9dEb4w5elYoTb8NFfeOunwwU7hsLO57hr/MFZxdNsDFkodHjIBqzQqe732OEPzLssbqpWU5YpHVjXu0buT6VMPCm9BVst+UKjjQ+TXhb2m1HJS95adtsfvXT+4viMkTQ6IFF5z9FiODpo3IIoUfKC4mqjW5DbjifaH+bSnGZaOXojMs7Umy9UQ3jNOu4g5qhoSVDYOrIDZsNyDaxMfMi5XYi2BnCcPGLbaxJ jamalex@wa
  richard:
    keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC/NIw+XcTs5ooMlo+fYOIzteQFH6EmCJ+4Losdplox6I1ph/57KYcbhYE8dWyb43/UfZmLxA1NXwidXDouZTKpcnbz6wn4uWM8kAk2pQ8EFPROlSlCuU0W2azzrci82J4gVj1++vCpHodVPqQ4zIJlvclpbD4Y0cy7z9HwqtF9uFGVwXAGsxqoCvBL0rV53fj+FSTBihHV1J/swsFSWsYUZLm3eqZg3pYggPhpTN3ndHOTBCciW4z21BFFD7J//P3ORu2rBsWRgUemg4n9k74VhfKNw1NEBnppTFDOTGZRIL20dHMq+YjkT5QEdkfsvJ/RxML1mz5Tazv1QStvQBfF richard.tibbles@gmail.com
  mike:
    keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEArDQ5HKDWXrXpmlzK6pKqP/u/5hcyEQ6vgpsnV2mneQnRCKKjeSVUx6KjVD4x8QlL1wK0VwgjxOVh7xHW5EhgV39iRa74qi9UCL44h7YRZoUL1OyPbj00A5tOUryZ4I8Mjha7r1A7Qx0fm7VvlLoPs2tGQJBNIIzk6ynpQB1y/vvlO9TsaoRftPLBZXcy9xvWqxpInOQ4OCa6Zn47lhHnEXu3qsF9XNQvqOfSqu4Cks9ukiDXuLObYcUAGnut46SsTR6WJTtm29zw6jrI94jDRXYr+BgdNkIl+8C/0G1t3tAAPoNlTmG88yXQ7RfpHCbV3Hn9wGHHUu6FWE4nRRFuFw== mike@laptop
  chandan:
    keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDHd4vpJty3bLFeJaUVnIZlBGMsPlDI3eKFnJ27T+foGgnQDm0MiTldPvy/tBCHwNxXAERU3EOzaYtkEqeoiA/bzDP2k3kjMlzjovv4+D0c4kmKmLSnDgIlK4B5PFWuYWrGQxkZwBgUSAOfkiXoZgVqrBcqdQcayjEVb5hhINmOyuSeXqMkvyaeXU+r2Ks9z7kdWj4od5CQ037tsMaZ/gm1OHJzenZxd2RcTt5iuKZA+Eg32JLyeLP9UiTP7uYPihaouhu8l+Z1e0c2G5az/UcOrMMTM/VEB/ChMr2MubMQvdEIBpLXnQDdJEbr2NyuQGnKzEjV1McgTavakeDlWxtr chandan@enigma
  antriksh:
    keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDE6MHlMn5ThW3w7E+iivq4LNi7vv38P/xd+apNly2uZBq3t5Kz5b8QxHvg0YtqeZCSFHxYAsa56QMighZ6WhcasMo3qZQc4u/9eaUCZJ1xcAG1K8uJM1UfYkYkK4tZj32wPEsVCEmGNx5c1vqE5rnAonG9EgyNiyvuJFJkyI3OoVlSHO8PGzr/4Mu6ojX1seS6wZIytkMtLupIcW+0eOzy5cFseqUUjD6+wR2oVhDMC9WpG2gitC4Q9YfFr5QCTpHbm6JSIRVLfrtEEaLctcHXXzg2fTXob75q8taGbiG08anq3ax4tfgm9SPoGW98Eov4kUrQqZf0jJHNzy8a8oEn Antriksh@Antrikshs-MacBook-Pro

permissions:
  gatehouse:
    - jamalex
  keep:
    - jamalex
    - aron
  scriptorium:
    - jamalex
    - aron
    - richard
  field:
    - jamalex
    - aron
    - richard
    - mike
  citadel:
    - jamalex
    - aron
  dungeon:
    - jamalex
    - aron
    - richard
  kitchen:
    - jamalex
    - aron
    - richard
  globe:
    - jamalex
    - aron
    - richard
    - mike
  troy:
    - jamalex
    - aron
    - richard
  banner:
    - jamalex
    - aron
    - richard
    - antriksh
  testbox:
    - mike
